### PR TITLE
Import studies from remote Mica instances

### PR DESCRIPTION
**Pull request by rljoia**
This Pull Request solve the issue #3904 and takes into account the comments in #3906.

All new keys in en.json weren't translated in fr.json. You can check this in fr.json -> keys with "Please translate" value.

You can check my modifications accessing [this filter](https://github.com/obiba/mica2/pull/3908/files/54f5675ca2f0ccffa5b66181a2be5be1cd591919..0509b3e67496e7f166a6913e1a3f92072edcd781).

### CODE REVIEW

**Comment by rljoia** [comment]
You can check my modifications accessing [this filter](https://github.com/obiba/mica2/pull/3908/files/54f5675ca2f0ccffa5b66181a2be5be1cd591919..0509b3e67496e7f166a6913e1a3f92072edcd781).

**Comment by kazoompa** [comment]
Hi Rafael,

I think something went wrong when you created the PR branch, you have too many modified files. I believe your first PR had far fewer modified files.

**Comment by rljoia** [comment]
> Hi Rafael,
> 
> I think something went wrong when you created the PR branch, you have too many modified files. I believe your first PR had far fewer modified files.

I will check this. It was unexpected, once before include my modifications, I updated my master with the Obiba's master and after that, I created a new branch based on master.

**Comment by rljoia** [comment]
Ramin (@kazoompa ), 

I believe the [new pull request](https://github.com/obiba/mica2/pull/3909) it's as expected. Thanks for the support.

**Pull request closed without merging**
