### PR TITLE
Feature/use schema form field for studies

### PR DESCRIPTION
**Pull request by firone**

### CODE REVIEW

**Comment by firone** [comment]
Two problem I'll fix before :
- https://jira.obiba.org/jira/browse/MK-1135
- https://jira.obiba.org/jira/browse/MK-1142

**Comment by ymarcon** [comment]
Tested adding new study:
* form validation does not highlight fields in error
* objectives field is missing
* study design enums are not translated

**Comment by ymarcon** [comment]
Tested adding new population:
* on empty form save: error 500
* once population saved, no DCE can be added

**Comment by ymarcon** [comment]
Tested member addition:
* failure on save

**Comment by ymarcon** [comment]
Please test before resubmitting this PR.

**Pull request closed without merging**
