### PR TITLE
Import studies from remote Mica instances

### PR DESCRIPTION
**Pull request by rljoia**
This Pull Request solve the issue [3904](https://github.com/obiba/mica2/issues/3904).
Key Attention Points:
 - All new keys in en.json weren't translated in fr.json. You can check this in fr.json -> keys with "Please translate" value.
- Added protoc binary for MacOS. The version 2.5.0 doesn't has support for MacOS, so I had to update for the last version (3.11.4). To keep the compatibility, all *.proto have now  `syntax = "proto2";` in the first line.
- ng-obiba dependency was updated from 1.9.8 to 2.0.0 after not found the 1.9.8 dependency during the build;
- some few dependencies in package.json had to be updated after build problems.

### CODE REVIEW

**Comment by kazoompa** [comment]
Hi Rafael,

Great job, just pulled your PR and played around. I have added a few comments above. Here are a few more:

- You branch is not up-to-date, please make sure you are in sync with master (you won't need to fix 
- It would be great if you could build on a Linux machine (VM - Fedora, Ubuntu, Debian, etc) as well. This is the DEV OS that our other collaborators and us use. For example, I found out that your protobuf version binary was not executable and did not work (segmentation fault). I used [this](https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip) verison.
- You better install this utility for Node and other dependency management: [NVM](https://github.com/nvm-sh/nvm)
Once this is installed you can set your default version to the latest: `lts/erbium`

Once the above is done, we can do one more run of your code and I let Yannick merge.

**Comment by rljoia** [comment]
> Hi Rafael,
> 
> Great job, just pulled your PR and played around. I have added a few comments above. Here are a few more:
> 
> * You branch is not up-to-date, please make sure you are in sync with master (you won't need to fix ng-obiba version)
> * It would be great if you could build on a Linux machine (VM - Fedora, Ubuntu, Debian, etc) as well. This is the DEV OS that our other collaborators and us use. For example, I found out that your protobuf version binary was not executable and did not work (segmentation fault). I used [this](https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip) verison.
> * You better install this utility for Node and other dependency management: [NVM](https://github.com/nvm-sh/nvm)
>   Once this is installed you can set your default version to the latest: `lts/erbium`
> 
> Once the above is done, we can do one more run of your code and I let Yannick merge.

Hi Ramin,

I followed the steps that you suggested. I noticed that Mica UI changed a lot, but I'm not sure if I have to do some extra configuration, because I'm not succeed in access the studies form anymore. As you can [see in the picture](https://user-images.githubusercontent.com/6485356/81121457-b962a380-8f26-11ea-8d63-5fbb4ce733f1.png), I'm getting some errors related with "Query execution error [no such index]". I noticed that this error also occur in other forms. It's also possible to notice that 'studies-callout' appears on the the screen, but it doesn't make any sense.

Is there any other necessary step to run this new version of Mica locally?

Thanks,
Rafael Lima Joia

**Comment by kazoompa** [comment]
Hi Rafael,

These are changes made in [Mica 4.0](https://www.obiba.org/pages/news/release/mica2/4.0/) release. What you see are the public static pages, a replacement/alternative to the Drupal public pages.

In order to see the admin Study form you must login as administrator: click the padlock icon in the footer (image) or type: `https://<your-mica-server>/signin?redirect=/admin`.

If you do not wish to use these pages just now you can configure a redirect to `https://<your-mica-server>/admin` .

Here is an example of an Apache config:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
     ServerName mica.<domain>.org

     ProxyRequests Off
     ProxyPreserveHost On
     ProxyPass / http://localhost:8082/
     ProxyPassReverse / http://localhost:8082/

     <Proxy *>
         Order deny,allow
         Allow from all
     </Proxy>

RewriteEngine on
RewriteCond %{REQUEST_URI} ^/$
RewriteRule (.*) /signin?redirect=/admin [R=301]

...

</VirtualHost>
</IfModule>
```

As for the `No Such Index`, you may need to reindex documents.

Once you made your changes we can pull your PR for further tests and also find some adequate translations for French (our friends Google translate and Yannick :grin:).

Best,

**Comment by ymarcon** [comment]
See also Mica 4.0 release announcement wit details about the public pages:
https://www.obiba.org/pages/news/release/mica2/4.0/

**Comment by rljoia** [comment]
The PR will be done from other branch (inesctec-dev-pr).

**Pull request closed without merging**
