### PR TITLE
MK-1279 - add earliestStart and containerId properties to datasetVari…

### PR DESCRIPTION
**Pull request by meek0**
…ables of type Study.

The variables will thus be ordered by:
1- study id or network id (in the case of dataschema variables)
2- dce start date (for study variables)
3- dataset id (useful for dataschema variables because dce start date is not set)
4- index

This way, a study variable is ordered chronologically within its study.

The same variable value for earliestStart is used in dataset to order them chronologically (first group datsets by study id then use dce's start date to order them further).

### CODE REVIEW

**Comment by ymarcon** [comment]
What happens if the DCE dates changes and the variables are not re-indexed?

**Comment by meek0** [comment]
All the datasets related to the study that was changed will have to be reindexed. There is no way to know what dce changed to target a specific dataset. This can be done automatically or at the discration of the user.

**Comment by meek0** [comment]
Another similar use case would be if a user decides to delete a population or dce. A dataset will still refer to a deleted population/dce until a direct user action is made. Currently, there is no constraint on a document field's change, only on its deletion.

**Comment by meek0** [comment]
The Jira https://jira.obiba.org/jira/browse/MK-1360 would be the proposed solution because as in, before deleting a study we check for its dependencies and if there are we warn about these.

Considering that the dce start date changing is not really vital, a warning can be issued, but we should stop the user from deleting study, population or dce and issue a dependency error.

**Pull request merged**
