### PR TITLE
Feature/harmonization initiative protocol

### PR DESCRIPTION
**Pull request by meek0**

### CODE REVIEW

**Comment by ymarcon** [comment]
After adding 2 individual studies and then 2 harmo initiatives to the cart, in the cart page only the individual studies are shown (but the count of studies is still 4)

image

**Comment by ymarcon** [comment]
* Add individual studies to the cart
* Go to cart page, studies tab
* Click on the search button: all the individual studies are shown, not just the ones in the cart 

Note: the search from cart works for harmo init and collected/harmo variables

**Comment by ymarcon** [comment]
Problem with the General config: it is not possible to have a config WITHOUT (collected and protocols) datasets that allows Harmo initiative only or both Individual study + Harmo initiative.

**Comment by ymarcon** [comment]
Simplify the Search button, when there is only one option

image

**Comment by ymarcon** [comment]
* Add individual studies to the cart
* Add harmo init to the cart
* Go to cart page, studies tab: it shows the individual studies
* Click on the compare button (no item selected): it compares the harmo inits.

Similarly, the Delete buttons removes the harmo inits from the cart, not the individual studies.

**Comment by ymarcon** [comment]
When harmo is NOT selected in the General config, align on same row:

image

Expected:

image

**Comment by ymarcon** [comment]
Design an icon for Harmo Init and for Dataschema Variables, because right now these are the same as their individual flavor.

image

**Comment by ymarcon** [comment]
Sometime the selection model in the cart/list does not work: it should be always possible to select the items to delete or to copy into a list (variables) or to compare (studies).

**Comment by ymarcon** [comment]
Table pager is not reset when changing from **Indivual** to **Harmonization** type, which could make items not visible.

* add more than 50 individual variables to the cart
* add a few harmo variables to the cart
* go to cart
* select page 2 of individual variables
* click on the harmo variables list: nothing is visible because page 2 is empty for that type

**Comment by ymarcon** [comment]
The cart of networks is broken:
* selection column's header is missing
* the dropdown for selecting individual/harmo is not relevant

**Comment by ymarcon** [comment]
In the cart/list, do not show the Individual/Harmonization option when config excludes Individual/Harmonization datasets.

**Comment by meek0** [comment]
sub tabs with counts would require another query. the /cart and /list pages use the same api as the search page.
don't see a clean way to delete all variables of same type in a cart/list. again same api as search and don't have all ids by type other than by searching a receiving everything.

**Comment by ymarcon** [comment]
unless you get the indiv/harmo items counts in the controller for SSR.

**Comment by ymarcon** [comment]
The table pager is visible when the list of items is empty:

image

**Comment by ymarcon** [comment]
The collected dataset uses the dataschema variable icon instead of the regular one:
image

**Comment by ymarcon** [comment]
The individual study uses the harmo protocol and the dataschema variable icons instead of the regular ones:

image

**Comment by kazoompa** [comment]
> The collected dataset uses the dataschema variable icon instead of the regular one: image

Will also check the one in Study page...

**Comment by ymarcon** [comment]
* Add some individual studies and some harmo initiatives to the cart
* Go to the cart, select Studies tab

=> Click on Search for the Individual studies: there is an extra "Type of study" criteria despite it is implicit
image

* Go back to the Cart of Studies

=> Click on Search for the harmo initiatives: the "Cart" criteria is missing
image

**Comment by ymarcon** [comment]
There is still the "Type of study" criteria when clicking on the search button in the cart of studies. It is useless and cannot be removed.

image

There is no such criteria when searching from the cart of variables.

**Comment by ymarcon** [comment]
Do not forget to document the added setting `dataschemaIcon` and `initiativeIcon` in the page:
https://micadoc.obiba.org/en/latest/admin/pub-configuration.html#general-settings

**Comment by ymarcon** [comment]
And also change the documentation about the Harmo model
https://micadoc.obiba.org/en/latest/documents.html

**Pull request merged**
