### PR TITLE
Created a list to filter and sort menu items

### PR DESCRIPTION
**Pull request by kazoompa**
References #4060

### CODE REVIEW

**Comment by ymarcon** [comment]
Maybe not specific enough: this "visibleTargets" setting affects only the menus, not the Lists' tabs. Could you rename to "searchCriteriaMenus" ? (or something similar)

**Comment by kazoompa** [comment]
I did not share the same logic as there are cases, such as Maelstrom, where the order of the TABs do not follow that of the sidebar menu (see below). I could however use a similar setting to show/hide the TABs.

image

**Comment by ymarcon** [comment]
That's what I say, menu and lists targets can be different, then "visibleTargets" is confusing as it applies only to menus.

**Comment by kazoompa** [comment]
I have changed the name, working on the TABs...

**Pull request merged**
